spring:
  application:
    name: central-process-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false #Show the query in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  grpc:
    server:
      port: ${GRPC_PORT}
      enable-reflection: false # Enables gRPC server reflection, allowing clients to dynamically discover services and methods
      security:
        enabled: ${GRPC_HTTPS}
        certificateChain: ${GRPC_HTTPS_CERTIFICATE}
        privateKey: ${GRPC_HTTPS_PRIVATE_KEY}
        trustCertCollection: ${GRPC_HTTPS_TRUSTED_CERTIFICATE_COLLECTION}

logging:
  config: classpath:logback.xml

application:
  keycloak:
    public-key: ${KEYCLOAK_PUBLIC_KEY}
  emergency:
    task:
      clean-old-call: 5 #Time in seconds (for the schedule task)
      max-old-call: 30 #Time in seconds
